service: tobb-kgk-wcoop-serverless

provider:
  name: aws
  runtime: java11
  profile: kgk-user
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchGetItem
        - dynamodb:BatchWriteItem
      Resource: "arn:aws:dynamodb:eu-west-1:*:*"

package:
  artifact: target/tobb-kgk-wcoop-0.1.jar

functions:
  tobb-kgk-micronaut-wcoop:
    handler: com.kgk.LambdaHandler::handleRequest
#    handler: io.micronaut.function.aws.proxy.MicronautLambdaHandler
    environment:
      MICRONAUT_ENVIRONMENTS: ${opt:stage, 'dev'}
    events:
      - http:
          path: /{proxy+}
          method: get
          cors: true
      - http:
          path: /{proxy+}
          method: post
          cors: true
      - http:
          path: /{proxy+}
          method: put
          cors: true
      - http:
          path: /{proxy+}
          method: delete
          cors: true
      - http:
          path: /{proxy+}
          method: patch
          cors: true

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Users
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: city
            AttributeType: S
          - AttributeName: roleId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: usersByCity
            KeySchema:
              - AttributeName: city
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
          - IndexName: usersByCityAndRoleId
            KeySchema:
              - AttributeName: city
                KeyType: HASH
              - AttributeName: roleId
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    catalogsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Catalogs
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: catalogId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: catalogId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    newsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: News
        AttributeDefinitions:
          - AttributeName: newsId
            AttributeType: S
          - AttributeName: updatedAt
            AttributeType: N
          - AttributeName: city
            AttributeType: S
        KeySchema:
          - AttributeName: newsId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: newsByCity
            KeySchema:
              - AttributeName: city
                KeyType: HASH
              - AttributeName: updatedAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    meetingsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Meetings
        AttributeDefinitions:
          - AttributeName: meetingId
            AttributeType: S
          - AttributeName: updatedAt
            AttributeType: N
          - AttributeName: city
            AttributeType: S
        KeySchema:
          - AttributeName: meetingId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: meetingsByCity
            KeySchema:
              - AttributeName: city
                KeyType: HASH
              - AttributeName: updatedAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    groupsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Groups
        AttributeDefinitions:
          - AttributeName: groupId
            AttributeType: S
          - AttributeName: city
            AttributeType: S
          - AttributeName: createdBy
            AttributeType: S
        KeySchema:
          - AttributeName: groupId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: groupsByCreatedBy
            KeySchema:
              - AttributeName: createdBy
                KeyType: HASH
              - AttributeName: city
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    groupMembersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: GroupMembers
        AttributeDefinitions:
        - AttributeName: groupId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        KeySchema:
          - AttributeName: groupId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: groupMembersByUserId
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    groupMessagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: GroupMessages
        AttributeDefinitions:
          - AttributeName: groupId
            AttributeType: S
          - AttributeName: messageId
            AttributeType: S
          - AttributeName: sendAt
            AttributeType: N
        KeySchema:
          - AttributeName: groupId
            KeyType: HASH
          - AttributeName: messageId
            KeyType: RANGE
        LocalSecondaryIndexes:
          - IndexName: messagesByGroupId
            KeySchema:
              - AttributeName: groupId
                KeyType: HASH
              - AttributeName: sendAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    registerFormsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: RegisterForms
        AttributeDefinitions:
          - AttributeName: registerId
            AttributeType: S
          - AttributeName: city
            AttributeType: S
          - AttributeName: approved
            AttributeType: S
        KeySchema:
          - AttributeName: registerId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: registerFormsByCity
            KeySchema:
              - AttributeName: city
                KeyType: HASH
              - AttributeName: approved
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    rolesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Roles
        AttributeDefinitions:
          - AttributeName: roleName
            AttributeType: S
          - AttributeName: roleId
            AttributeType: S
        KeySchema:
          - AttributeName: roleName
            KeyType: HASH
          - AttributeName: roleId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    deletedItems:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: DeletedItems
        AttributeDefinitions:
          - AttributeName: whichTable
            AttributeType: S
          - AttributeName: deletedTime
            AttributeType: N
          - AttributeName: originalId
            AttributeType: S
        KeySchema:
          - AttributeName: whichTable
            KeyType: HASH
          - AttributeName: deletedTime
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: itemsByOriginalId
            KeySchema:
              - AttributeName: whichTable
                KeyType: HASH
              - AttributeName: originalId
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
