package com.kgk.model.admin;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import edu.umd.cs.findbugs.annotations.NonNull;
import io.micronaut.core.annotation.Introspected;

import javax.validation.constraints.NotBlank;

@Introspected
@DynamoDBTable(tableName = "Advertisement")
public class Advertisement {

    @NonNull
    @NotBlank
    private Integer advId;

    @NonNull
    private String advHead;

    @NonNull
    private String advBody;  //string mi pdf mi(byte[] ile almamız mı gerekir o zaman?)

    @NonNull
    private Integer userID;

    @NonNull
    @NotBlank
    private Long requestDate;

    private Integer roleId;

    @NonNull
    private boolean approved;


    public Advertisement(){
    }

    @DynamoDBHashKey(attributeName = "AdvertisementID")
    @DynamoDBAutoGeneratedKey
    @NonNull
    public Integer getAdvId() {
        return advId;
    }

    public void setAdvId(@NonNull Integer advId) {
        this.advId = advId;
    }

    @DynamoDBAttribute(attributeName = "AdvertisementHead")
    @NonNull
    public String getAdvHead() {
        return advHead;
    }

    public void setAdvHead(@NonNull String advHead) {
        this.advHead = advHead;
    }

    @DynamoDBAttribute(attributeName = "AdvertisementBody")
    @NonNull
    public String getAdvBody() {
        return advBody;
    }

    public void setAdvBody(@NonNull String advBody) {
        this.advBody = advBody;
    }

    @DynamoDBAttribute(attributeName = "RequestedBy")
    @NonNull
    public Integer getUserID() {
        return userID;
    }

    public void setUserID(@NonNull Integer userID) {
        this.userID = userID;
    }

    @DynamoDBAttribute(attributeName = "RequestDate")
    @NonNull
    public Long getRequestDate() {
        return requestDate;
    }

    public void setRequestDate(@NonNull Long requestDate) {
        this.requestDate = requestDate;
    }

    @DynamoDBAttribute(attributeName = "RoleID")
    public Integer getRoleId() {
        return roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    @DynamoDBAttribute(attributeName = "Approved")
    public boolean isApproved() {
        return approved;
    }

    public void setApproved(boolean approved) {
        this.approved = approved;
    }
}
