package com.kgk.model.admin;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import edu.umd.cs.findbugs.annotations.NonNull;
import io.micronaut.core.annotation.Introspected;

import javax.validation.constraints.NotBlank;

@Introspected
@DynamoDBTable(tableName = "CVBank")
public class CV {

    @NonNull
    @NotBlank
    private Integer CVId;

    @NonNull
    @NotBlank
    private Integer userId;

    @NonNull
    private byte[] CVFile; //PDF için şimdilik byte[] dedik ama olur mu?

    @NonNull
    private Long uploadDate;

    private Integer roleId;

    @NotBlank
    private boolean approved;

    public CV(){}

    @DynamoDBHashKey(attributeName = "CVID")
    @DynamoDBAutoGeneratedKey
    @NonNull
    public Integer getCVId() {
        return CVId;
    }

    public void setCVId(@NonNull Integer CVId) {
        this.CVId = CVId;
    }

    @DynamoDBAttribute(attributeName = "UserID")
    @NonNull
    public Integer getUserId() {
        return userId;
    }

    public void setUserId(@NonNull Integer userId) {
        this.userId = userId;
    }

    @DynamoDBAttribute(attributeName = "CVFile")
    @NonNull
    public byte[] getCVFile() {
        return CVFile;
    }

    public void setCVFile(@NonNull byte[] CVFile) {
        this.CVFile = CVFile;
    }

    @DynamoDBAttribute(attributeName = "RoleID")
    @NonNull
    public Integer getRoleId() {
        return roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    @DynamoDBAttribute(attributeName = "UploadDate")
    @NonNull
    public Long getUploadDate() {
        return uploadDate;
    }

    public void setUploadDate(@NonNull Long uploadDate) {
        this.uploadDate = uploadDate;
    }

    @DynamoDBAttribute(attributeName = "Approved")
    public boolean isApproved() {
        return approved;
    }

    public void setApproved(boolean approved) {
        this.approved = approved;
    }
}
