package com.kgk.model.admin;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import edu.umd.cs.findbugs.annotations.NonNull;
import io.micronaut.core.annotation.Introspected;

import javax.validation.constraints.NotBlank;

@Introspected
@DynamoDBTable(tableName = "CVs")
public class CV {

    @NonNull
    @NotBlank
    private String cvId;

    @NonNull
    @NotBlank
    private String uploadedBy; //userid yerine

    @NonNull
    private String cvFile;

    @NonNull
    private Long uploadDate;

    private String roleId;

    @NotBlank
    private boolean approved;

    public CV(){}

    @DynamoDBHashKey(attributeName = "cvId")
    @DynamoDBAutoGeneratedKey
    @NonNull
    public String getCvId() {
        return cvId;
    }

    public void setCvId(@NonNull String cvId) {
        this.cvId = cvId;
    }

    @DynamoDBRangeKey(attributeName = "uploadedBy")
    @NonNull
    public String getUploadedBy() {
        return uploadedBy;
    }

    public void setUploadedBy(@NonNull String uploadedBy) {
        this.uploadedBy = uploadedBy;
    }

    @DynamoDBAttribute(attributeName = "cvFile")
    @NonNull
    public String getCvFile() {
        return cvFile;
    }

    public void setCvFile(@NonNull String cvFile) {
        this.cvFile = cvFile;
    }

    @DynamoDBAttribute(attributeName = "roleId")
    @NonNull
    public String getRoleId() {
        return roleId;
    }

    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    @DynamoDBAttribute(attributeName = "uploadDate")
    @NonNull
    public Long getUploadDate() {
        return uploadDate;
    }

    public void setUploadDate(@NonNull Long uploadDate) {
        this.uploadDate = uploadDate;
    }

    @DynamoDBAttribute(attributeName = "approved")
    public boolean isApproved() {
        return approved;
    }

    public void setApproved(boolean approved) {
        this.approved = approved;
    }
}
