package com.kgk.model.admin;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import edu.umd.cs.findbugs.annotations.NonNull;
import io.micronaut.core.annotation.Introspected;

import javax.validation.constraints.NotBlank;

@Introspected
@DynamoDBTable(tableName = "CVs")
public class CV {

    @NonNull
    @NotBlank
    private String cvId;

    @NonNull
    @NotBlank
    private String uploadedby; //userid yerine

    @NonNull
    private String cvFile; //PDF için şimdilik byte[] dedik ama olur mu?

    @NonNull
    private Long uploadDate;

    private String roleId;

    @NotBlank
    private boolean approved;

    public CV(){}

    @DynamoDBHashKey(attributeName = "cvId")
    @DynamoDBAutoGeneratedKey
    @NonNull
    public String getCVId() {
        return cvId;
    }

    public void setCVId(@NonNull String cvId) {
        this.cvId = cvId;
    }

    @DynamoDBRangeKey(attributeName = "uploadedby")
    @NonNull
    public String getUploadedby() {
        return uploadedby;
    }

    public void setUploadedby(@NonNull String userId) {
        this.uploadedby = uploadedby;
    }

    @DynamoDBAttribute(attributeName = "CVFile")
    @NonNull
    public String getCVFile() {
        return cvFile;
    }

    public void setCVFile(@NonNull String cvFile) {
        this.cvFile = cvFile;
    }

    @DynamoDBAttribute(attributeName = "RoleID")
    @NonNull
    public String getRoleId() {
        return roleId;
    }

    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    @DynamoDBAttribute(attributeName = "UploadDate")
    @NonNull
    public Long getUploadDate() {
        return uploadDate;
    }

    public void setUploadDate(@NonNull Long uploadDate) {
        this.uploadDate = uploadDate;
    }

    @DynamoDBAttribute(attributeName = "Approved")
    public boolean isApproved() {
        return approved;
    }

    public void setApproved(boolean approved) {
        this.approved = approved;
    }
}
