package com.kgk.model.admin;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import edu.umd.cs.findbugs.annotations.NonNull;
import io.micronaut.core.annotation.Introspected;

@Introspected
@DynamoDBTable(tableName = "News")
public class News {

    @NonNull
    private String newsId; //hash key

    @NonNull
    private Long publishDate;    //range key

    private String newsTitle;

    private String newsBody;

    private boolean meeting;

    private Long startTime;

    private Long endTime;

    private String meetingPlace;

    private String meetingUrl;

    public News() {}

    // Partition key
    @DynamoDBHashKey(attributeName = "newsId")
    @DynamoDBAutoGeneratedKey
    @NonNull
    public String getNewsId() {
        return newsId;
    }

    public void setNewsId(@NonNull String newsId) {
        this.newsId= newsId;
    }

    @DynamoDBRangeKey(attributeName = "publishDate")
    public Long getPublishDate() {
        return publishDate;
    }

    public void setPublishDate(Long publishDate) {
        this.publishDate = publishDate;
    }

    @DynamoDBAttribute(attributeName = "newsTitle")
    public String getNewsTitle() {
        return newsTitle;
    }

    public void setNewsTitle(String newsTitle) {
        this.newsTitle = newsTitle;
    }

    @DynamoDBAttribute(attributeName = "newsBody")
    public String getNewsBody() {
        return newsBody;
    }

    public void setNewsBody(String newsBody) {
        this.newsBody = newsBody;
    }

    @DynamoDBAttribute(attributeName = "meeting")
    public boolean isMeeting() {
        return meeting;
    }

    public void setMeeting(boolean meeting) {
        this.meeting = meeting;
    }

    @DynamoDBAttribute(attributeName = "startTime")
    public Long getStartTime() {
        return startTime;
    }

    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    @DynamoDBAttribute(attributeName = "endTime")
    public Long getEndTime() {
        return endTime;
    }

    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    @DynamoDBAttribute(attributeName = "meetingPlace")
    public String getMeetingPlace() {
        return meetingPlace;
    }

    public void setMeetingPlace(String meetingPlace) {
        this.meetingPlace = meetingPlace;
    }

    @DynamoDBAttribute(attributeName = "meetingUrl")
    public String getMeetingUrl() {
        return meetingUrl;
    }

    public void setMeetingUrl(String meetingUrl) {
        this.meetingUrl = meetingUrl;
    }

}
