package com.kgk.model;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import edu.umd.cs.findbugs.annotations.NonNull;
import io.micronaut.core.annotation.Introspected;

@Introspected
@DynamoDBTable(tableName = "News")
public class News {

    private Integer newsId;

    @NonNull
    private Integer userId;  //tüm member'ların news ekleme hakkı olacak mı?

    @NonNull
    private String newsTitle;

    @NonNull
    private String newsBody; //news string mi olacak PDF mi

    private Long publishDate;

    public News() {}
    // Partition key
    @DynamoDBHashKey(attributeName = "NewsId")
    @DynamoDBAutoGeneratedKey

    @NonNull
    public Integer getNewsId() {
        return newsId;
    }

    public void setNewsId(@NonNull Integer newsId) {
        newsId = newsId;
    }

    @DynamoDBAttribute(attributeName = "userId")
    @NonNull
    public Integer getUserId() {
        return userId;
    }

    public void setUserId(@NonNull Integer userId) {
        this.userId = userId;
    }
    @DynamoDBAttribute(attributeName = "newsTitle")
    @NonNull
    public String getNewsTitle() {
        return newsTitle;
    }

    public void setNewsTitle(@NonNull String newsTitle) {
        newsTitle = newsTitle;
    }
    @DynamoDBAttribute(attributeName = "NewsBody")
    @NonNull
    public String getNewsBody() {
        return newsBody;
    }

    public void setNewsBody(@NonNull String newsBody) {
        newsBody = newsBody;
    }

    @DynamoDBAttribute(attributeName = "publishDate")
    public Long getPublishDate() {
        return publishDate;
    }

    public void setPublishDate(Long publishDate) {
        publishDate = publishDate;
    }
}
