package com.kgk.model;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import edu.umd.cs.findbugs.annotations.NonNull;
import io.micronaut.core.annotation.Introspected;

@Introspected
@DynamoDBTable(tableName = "News")
public class News {

    private String newsId; //hash key

    @NonNull
    private String userId;  //range key (tüm member'ların news ekleme hakkı olacak mı?)

    @NonNull
    private String newsTitle;

    @NonNull
    private String newsBody;

    private Long publishDate;

    public News() {}
    // Partition key
    @DynamoDBHashKey(attributeName = "newsId")
    @DynamoDBAutoGeneratedKey

    @NonNull
    public String getNewsId() {
        return newsId;
    }

    public void setNewsId(@NonNull String newsId) {
        newsId = newsId;
    }

    @DynamoDBRangeKey(attributeName = "userId")
    @NonNull
    public String getUserId() {
        return userId;
    }

    public void setUserId(@NonNull String userId) {
        this.userId = userId;
    }
    @DynamoDBAttribute(attributeName = "newsTitle")
    @NonNull
    public String getNewsTitle() {
        return newsTitle;
    }

    public void setNewsTitle(@NonNull String newsTitle) {
        newsTitle = newsTitle;
    }
    @DynamoDBAttribute(attributeName = "NewsBody")
    @NonNull
    public String getNewsBody() {
        return newsBody;
    }

    public void setNewsBody(@NonNull String newsBody) {
        newsBody = newsBody;
    }

    @DynamoDBAttribute(attributeName = "publishDate")
    public Long getPublishDate() {
        return publishDate;
    }

    public void setPublishDate(Long publishDate) {
        publishDate = publishDate;
    }
}
