package com.kgk.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import edu.umd.cs.findbugs.annotations.NonNull;
import io.micronaut.core.annotation.Introspected;

import javax.validation.constraints.Email;
import javax.validation.constraints.NotBlank;
import java.util.ArrayList;
import java.util.List;

@Introspected
@DynamoDBTable(tableName = "Users")
public class User {

    @NonNull
    private String userId; //hash key

    @NonNull
    private String roleId; //range key

    @NonNull
    @NotBlank
    private String firstName;

    @NonNull
    @NotBlank
    private String lastName;

    @NonNull
    @NotBlank
    @Email
    private String email;

    @NonNull
    @NotBlank
    private String password;

    @NonNull
    @NotBlank
    private String tobbRegisterId;

    @NonNull
    @NotBlank
    private String phone;

    private String photo;

    private Long birthDate;

    private String sector;

    private String occupation;

    private List<Catalog> catalogList = new ArrayList<>();

    public User() {}

    // Partition key
    @DynamoDBHashKey(attributeName = "userId")
    @DynamoDBAutoGeneratedKey
    @NonNull
    public String getUserId() {
      return userId;
    }

    public void setUserId(@NonNull String userId) {
      this.userId = userId;
    }

    @DynamoDBRangeKey(attributeName = "roleId")
    @NonNull
    public String getRoleId() {
      return roleId;
    }

    public void setRoleId(@NonNull String roleId) {
      this.roleId = roleId;
    }

    @DynamoDBAttribute(attributeName = "firstName")
    @NonNull
    public String getFirstName() {
      return firstName;
    }

    public void setFirstName(@NonNull String firstName) {
      this.firstName = firstName;
    }

    @DynamoDBAttribute(attributeName = "lastName")
    @NonNull
    public String getLastName() {
      return lastName;
    }

    public void setLastName(@NonNull String lastName) {
      this.lastName = lastName;
    }

    @DynamoDBAttribute(attributeName = "email")
    @NonNull
    public String getEmail() {
      return email;
    }

    public void setEmail(@NonNull String email) {
      this.email = email;
    }

    @DynamoDBAttribute(attributeName = "password")
    @NonNull
    public String getPassword() {
      return password;
    }

    public void setPassword(@NonNull String password) { this.password = password; }

    @DynamoDBAttribute(attributeName = "photo")
    public String getPhoto() {
      return photo;
    }

    public void setPhoto(String photo) {
      this.photo = photo;
    }

    @DynamoDBAttribute(attributeName = "birthDate")
    public Long getBirthDate() {
      return birthDate;
    }

    public void setBirthDate(Long birthDate) {
      this.birthDate = birthDate;
    }

    @DynamoDBAttribute(attributeName = "occupation")
    public String getOccupation() {
      return occupation;
    }

    public void setOccupation(String occupation) {
      this.occupation = occupation;
    }

    @DynamoDBAttribute(attributeName = "phone")
    @NonNull
    public String getPhone() {
      return phone;
    }

    public void setPhone(@NonNull String phone) {
      this.phone = phone;
    }

    @DynamoDBAttribute(attributeName = "tobbRegisterId")
    @NonNull
    public String getTobbRegisterId() {
        return tobbRegisterId;
    }

    public void setTobbRegisterId(@NonNull String tobbRegisterId) {
        this.tobbRegisterId = tobbRegisterId;
    }

    @DynamoDBAttribute(attributeName = "sector")
    public String getSector() {
        return sector;
    }

    public void setSector(String sector) {
        this.sector = sector;
    }

    public List<Catalog> getCatalogList() {
        return catalogList;
    }

    public void setCatalogList(List<Catalog> catalogList) {
        this.catalogList = catalogList;
    }
}
