package com.kgk.model.profile;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import edu.umd.cs.findbugs.annotations.NonNull;
import io.micronaut.core.annotation.Introspected;

import javax.validation.constraints.NotBlank;

@Introspected
@DynamoDBTable(tableName = "Competences")
public class Competence {

    @NonNull
    private String compId; //hash key

    @NonNull
    private String userId; //range key

    @NonNull
    @NotBlank
    private String compName;

    @NonNull
    @NotBlank
    private String compDesc;

    // Partition key
    @DynamoDBHashKey(attributeName = "compId")
    @DynamoDBAutoGeneratedKey
    @NonNull
    public String getCompId() {
        return compId;
    }

    public void setCompId(@NonNull String compId) {
        this.compId = compId;
    }

    @DynamoDBRangeKey(attributeName = "userId")
    @NonNull
    public String getUserId() {
        return userId;
    }

    public void setUserId(@NonNull String userId) {
        this.userId = userId;
    }

    @DynamoDBAttribute(attributeName = "compName")
    @NonNull
    public String getCompName() {
        return compName;
    }

    public void setCompName(@NonNull String compName) {
        this.compName = compName;
    }

    @DynamoDBAttribute(attributeName = "compDesc")
    @NonNull
    public String getCompDesc() {
        return compDesc;
    }

    public void setCompDesc(@NonNull String compDesc) {
        this.compDesc = compDesc;
    }

}
