package com.kgk.model.profile;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import edu.umd.cs.findbugs.annotations.NonNull;
import io.micronaut.core.annotation.Introspected;

import javax.validation.constraints.NotBlank;

@Introspected
@DynamoDBTable(tableName = "Languages")
public class Language {

    @NonNull
    private String langId; //hash key

    @NonNull
    private String userId; //range key

    @NonNull
    @NotBlank
    private String langName;

    @NonNull
    @NotBlank
    private String langLevel;

    // Partition key
    @DynamoDBHashKey(attributeName = "langId")
    @DynamoDBAutoGeneratedKey
    @NonNull
    public String getLangId() {
        return langId;
    }

    public void setLangId(@NonNull String langId) {
        this.langId = langId;
    }

    @DynamoDBRangeKey(attributeName = "userId")
    @NonNull
    public String getUserId() {
        return userId;
    }

    public void setUserId(@NonNull String userId) {
        this.userId = userId;
    }

    @DynamoDBAttribute(attributeName = "langName")
    @NonNull
    public String getLangName() {
        return langName;
    }

    public void setLangName(@NonNull String langName) {
        this.langName = langName;
    }

    @DynamoDBAttribute(attributeName = "langLevel")
    @NonNull
    public String getLangLevel() {
        return langLevel;
    }

    public void setLangLevel(@NonNull String langLevel) {
        this.langLevel = langLevel;
    }

}
