package com.kgk.model.profile;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import edu.umd.cs.findbugs.annotations.NonNull;
import io.micronaut.core.annotation.Introspected;

import javax.validation.constraints.NotBlank;

@Introspected
@DynamoDBTable(tableName = "Projects")
public class Project {

    @NonNull
    private String projectId; //hash key

    @NonNull
    private String userId; //range key

    @NonNull
    @NotBlank
    private String projectName;

    private String projectDesc;

    @NonNull
    private Long projectDate;

    // Partition key
    @DynamoDBHashKey(attributeName = "projectId")
    @DynamoDBAutoGeneratedKey
    @NonNull
    public String getProjectId() {
        return projectId;
    }

    public void setProjectId(@NonNull String projectId) {
        this.projectId = projectId;
    }

    @DynamoDBRangeKey(attributeName = "userId")
    @NonNull
    public String getUserId() {
        return userId;
    }

    public void setUserId(@NonNull String userId) {
        this.userId = userId;
    }

    @DynamoDBAttribute(attributeName = "projectName")
    @NonNull
    public String getProjectName() {
        return projectName;
    }

    public void setProjectName(@NonNull String projectName) {
        this.projectName = projectName;
    }

    @DynamoDBAttribute(attributeName = "projectDesc")
    public String getProjectDesc() {
        return projectDesc;
    }

    public void setProjectDesc(String projectDesc) {
        this.projectDesc = projectDesc;
    }

    @DynamoDBAttribute(attributeName = "projectDate")
    @NonNull
    public Long getProjectDate() {
        return projectDate;
    }

    public void setProjectDate(@NonNull Long projectDate) {
        this.projectDate = projectDate;
    }

}
