package com.kgk.model.chat;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import edu.umd.cs.findbugs.annotations.NonNull;
import io.micronaut.core.annotation.Introspected;

import javax.validation.constraints.NotBlank;

@Introspected
@DynamoDBTable(tableName = "Groups")
public class Group {

    @NonNull
    private String groupId; //hash key

    @NonNull
    private Long createdAt; //range key

    @NonNull
    @NotBlank
    private String groupName;

    private String groupDesc;

    @NonNull
    private String createdBy; //userId

    public Group() {}

    // Partition key
    @DynamoDBHashKey(attributeName = "groupId")
    @DynamoDBAutoGeneratedKey
    @NonNull
    public String getGroupId() { return groupId; }

    public void setGroupId(String groupId) { this.groupId = groupId; }

    @DynamoDBRangeKey(attributeName = "createdAt")
    @NonNull
    public Long getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(@NonNull Long createdAt) {
        this.createdAt = createdAt;
    }

    @DynamoDBAttribute(attributeName = "groupName")
    @NonNull
    public String getGroupName() { return groupName; }

    public void setGroupName(@NonNull String groupName) { this.groupName = groupName; }

    @DynamoDBAttribute(attributeName = "groupDesc")
    public String getGroupDesc() { return groupDesc; }

    public void setGroupDesc(String groupDesc) { this.groupDesc = groupDesc; }

    @DynamoDBAttribute(attributeName = "createdBy")
    @NonNull
    public String getCreatedBy() { return createdBy; }

    public void setCreatedBy(@NonNull String createdBy) { this.createdBy = createdBy; }

}
